// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Sorted
{
public static class GPGSIDs
{
        public const string achievement_a_new_challenger = "CgkI59aojP0bEAIQFA"; // <GPGSID>
        public const string achievement_golden_god = "CgkI59aojP0bEAIQAg"; // <GPGSID>
        public const string achievement_a_case_of_chaos = "CgkI59aojP0bEAIQEA"; // <GPGSID>
        public const string leaderboard_order__moves = "CgkI59aojP0bEAIQBw"; // <GPGSID>
        public const string achievement_efficient_sort = "CgkI59aojP0bEAIQGg"; // <GPGSID>
        public const string leaderboard_order__timed = "CgkI59aojP0bEAIQBA"; // <GPGSID>
        public const string achievement_bust_a_move = "CgkI59aojP0bEAIQEw"; // <GPGSID>
        public const string leaderboard_chaos__moves = "CgkI59aojP0bEAIQDA"; // <GPGSID>
        public const string leaderboard_chaos__timed = "CgkI59aojP0bEAIQDg"; // <GPGSID>
        public const string achievement_gold_digger = "CgkI59aojP0bEAIQAQ"; // <GPGSID>
        public const string achievement_struck_gold = "CgkI59aojP0bEAIQAA"; // <GPGSID>
        public const string achievement_master_of_rotation = "CgkI59aojP0bEAIQFw"; // <GPGSID>
        public const string achievement_quick_sort = "CgkI59aojP0bEAIQEQ"; // <GPGSID>
        public const string achievement_squaring_off = "CgkI59aojP0bEAIQGw"; // <GPGSID>
        public const string achievement_total_groupie = "CgkI59aojP0bEAIQEg"; // <GPGSID>
        public const string achievement_spin_me_right_round = "CgkI59aojP0bEAIQFg"; // <GPGSID>
        public const string achievement_order_in_the_case = "CgkI59aojP0bEAIQDw"; // <GPGSID>
        public const string achievement_not_so_challenging = "CgkI59aojP0bEAIQFQ"; // <GPGSID>

}
}
